### ISSUE TITLE
sticky navigation bar

### ISSUE THREAD

**Issue by samsaara** [sharu725/gatok#15]
Hello, Thanks for the great product. May I know if it's possible to have the links under navigation available all the time ? Even if the pages are lengthy and I scroll down more. Currently  when I hover over to the left, I get a nice 3D transition but nothing is displayed as the content is up top and I had to scroll again to the top of the page to see `About`, `Contact` etc...

Is there any way to have them available all the time whenever I hover ? more like a toggleable sticky one ? :)

Thanks.

**Comment by sharu725** [comment]
I have tried it but unfortunately, it isn't possible. 
Since the whole body is applied with perspective CSS, nothing can be fixed to the viewport. Here is how it works [http://stackoverflow.com/a/36857029/5826491](http://stackoverflow.com/a/36857029/5826491).

There is a way if we remove perspective CSS from body, but you'll see no 3d rotation.

**Comment by samsaara** [comment]
hmm.. that's unfortunate :(
